variable "project_name" {
  description = "Resource name prefix (keep short)."
  type        = string
  default     = "agent-platform"
}

variable "environment" {
  description = "Environment label (dev/stage/prod)."
  type        = string
  default     = "dev"
}

variable "aws_region" {
  description = "AWS region."
  type        = string
  default     = "us-west-2"
}

variable "vpc_cidr" {
  description = "VPC CIDR."
  type        = string
  default     = "10.20.0.0/16"
}

variable "enable_dual_stack_public_edge" {
  description = "Enable IPv6 on the public ALB edge and public subnets. Private ECS tasks remain private."
  type        = bool
  default     = true
}

variable "public_hub_domain_name" {
  description = "Optional public DNS name for the gateway ALB HTTPS certificate, e.g. hub.zenith-research.ca. Leave empty for HTTP-only bootstrap."
  type        = string
  default     = ""
}

variable "enable_https_listener" {
  description = "Create the ALB HTTPS listener and redirect HTTP to HTTPS. Enable only after the ACM DNS validation record has propagated and the certificate is issued."
  type        = bool
  default     = false
}

variable "alb_idle_timeout_seconds" {
  description = "ALB idle timeout (increase for WebSockets/SSE stability)."
  type        = number
  default     = 3600
}

variable "log_retention_days" {
  description = "CloudWatch log retention in days."
  type        = number
  default     = 14
}

# Target cost profile: 0.25 vCPU / 0.5 GB RAM always on, per service
variable "task_cpu" {
  description = "Fargate CPU units (256 = 0.25 vCPU)."
  type        = number
  default     = 256
}

variable "task_memory" {
  description = "Fargate memory in MiB (512 = 0.5 GB)."
  type        = number
  default     = 512
}

variable "start_ecs_services" {
  description = "When false, ECS services are created with desired_count=0 so infrastructure/ECR/cert/storage can be applied before images exist. Set true after images are pushed."
  type        = bool
  default     = true
}

variable "gateway_desired_count" {
  description = "Desired task count for gateway-http when start_ecs_services is true. Keep at 1 while CLIENTS_DB_PATH uses SQLite; Postgres-backed deployments may raise this later."
  type        = number
  default     = 1
}

variable "gateway_clients_db_path" {
  description = "Persistent clients registry path for gateway-http Review SDK auth."
  type        = string
  default     = "/data/clients.db"
}

variable "gateway_reviews_data_dir" {
  description = "Writable reviews data directory for gateway-http review assets/submissions."
  type        = string
  default     = "/data/reviews"
}

variable "gateway_data_uid" {
  description = "POSIX uid used by the gateway container app user for the EFS access point."
  type        = number
  default     = 100
}

variable "gateway_data_gid" {
  description = "POSIX gid used by the gateway container app group for the EFS access point."
  type        = number
  default     = 101
}

variable "enable_clients_postgres" {
  description = "Create a private RDS Postgres database for the gateway Review SDK clients registry and configure gateway-http to use it."
  type        = bool
  default     = false
}

variable "clients_postgres_database_name" {
  description = "Database name for the clients registry Postgres database."
  type        = string
  default     = "hub_clients"
}

variable "clients_postgres_username" {
  description = "Master username for the clients registry Postgres database. Password is generated by RDS managed Secrets Manager."
  type        = string
  default     = "hub_clients"
}

variable "clients_postgres_instance_class" {
  description = "RDS instance class for clients registry Postgres."
  type        = string
  default     = "db.t4g.micro"
}

variable "clients_postgres_engine_version" {
  description = "Postgres engine version for clients registry RDS."
  type        = string
  default     = "16.6"
}

variable "clients_postgres_allocated_storage_gb" {
  description = "Initial allocated storage in GiB for clients registry RDS."
  type        = number
  default     = 20
}

variable "clients_postgres_max_allocated_storage_gb" {
  description = "Maximum autoscaled storage in GiB for clients registry RDS."
  type        = number
  default     = 100
}

variable "clients_postgres_backup_retention_days" {
  description = "Backup retention in days for clients registry RDS."
  type        = number
  default     = 7
}

variable "clients_postgres_backup_window" {
  description = "Preferred backup window for clients registry RDS."
  type        = string
  default     = "08:00-09:00"
}

variable "clients_postgres_maintenance_window" {
  description = "Preferred maintenance window for clients registry RDS."
  type        = string
  default     = "sun:09:00-sun:10:00"
}

variable "clients_postgres_deletion_protection" {
  description = "Enable deletion protection for clients registry RDS."
  type        = bool
  default     = true
}

variable "runtime_desired_count" {
  description = "Desired task count for runtime-grpc."
  type        = number
  default     = 1
}

variable "sandbox_desired_count" {
  description = "Desired task count for tool-sandbox."
  type        = number
  default     = 1
}

# Queue must stay at 1 — SQLite is single-writer and the EFS access point is not
# safe for concurrent writers. Scale by increasing throughput, not replicas.
variable "queue_desired_count" {
  description = "Desired task count for queue (must be 1 — SQLite single-writer constraint)."
  type        = number
  default     = 1
}

variable "image_tag" {
  description = "Image tag pushed to the ECR repos for each service."
  type        = string
  default     = "latest"
}

variable "qdrant_url" {
  description = "External Qdrant endpoint URL (Qdrant Cloud)."
  type        = string
}

variable "qdrant_api_key" {
  description = "Qdrant API key. If set, it will be stored in Terraform state."
  type        = string
  sensitive   = true
  default     = ""
}

variable "review_access_admin_token" {
  description = "Bearer token for operator-only Review Access rotation API. If set, it will be stored in Terraform state; prefer setting the Secrets Manager value out-of-band for production."
  type        = string
  sensitive   = true
  default     = ""
}

variable "cors_allow_origins" {
  description = "CORS_ALLOW_ORIGINS for gateway-http."
  type        = string
  default     = "https://example.com"
}

variable "max_body_bytes" {
  description = "MAX_BODY_BYTES for gateway-http."
  type        = number
  default     = 262144
}

variable "tool_dir" {
  description = "Tool manifest directory inside the container."
  type        = string
  default     = "/app/libs/tools"
}

variable "tool_default_timeout_ms" {
  description = "Default tool timeout (ms)."
  type        = number
  default     = 5000
}

variable "tool_default_max_memory_mb" {
  description = "Default tool max memory (MB)."
  type        = number
  default     = 128
}

variable "kb_vector_dim" {
  description = "KB vector dimension (must match existing seeded collection)."
  type        = number
  default     = 256
}

variable "qdrant_collection" {
  description = "Qdrant collection name for KB."
  type        = string
  default     = "kb_documents"
}

variable "enable_execute_command" {
  description = "Enable ECS Exec on services."
  type        = bool
  default     = false
}
