# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentRuntimeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitUserMessage = channel.unary_unary(
                '/agent.v1.AgentRuntime/SubmitUserMessage',
                request_serializer=agent__pb2.SubmitUserMessageRequest.SerializeToString,
                response_deserializer=agent__pb2.SubmitUserMessageResponse.FromString,
                _registered_method=True)
        self.StreamRuntimeEvents = channel.unary_stream(
                '/agent.v1.AgentRuntime/StreamRuntimeEvents',
                request_serializer=agent__pb2.StreamRuntimeEventsRequest.SerializeToString,
                response_deserializer=agent__pb2.RuntimeEvent.FromString,
                _registered_method=True)
        self.SearchKnowledge = channel.unary_unary(
                '/agent.v1.AgentRuntime/SearchKnowledge',
                request_serializer=agent__pb2.SearchKnowledgeRequest.SerializeToString,
                response_deserializer=agent__pb2.SearchKnowledgeResponse.FromString,
                _registered_method=True)
        self.InvokeTool = channel.unary_unary(
                '/agent.v1.AgentRuntime/InvokeTool',
                request_serializer=agent__pb2.InvokeToolRequest.SerializeToString,
                response_deserializer=agent__pb2.InvokeToolResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/agent.v1.AgentRuntime/HealthCheck',
                request_serializer=agent__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=agent__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class AgentRuntimeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitUserMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRuntimeEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchKnowledge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitUserMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitUserMessage,
                    request_deserializer=agent__pb2.SubmitUserMessageRequest.FromString,
                    response_serializer=agent__pb2.SubmitUserMessageResponse.SerializeToString,
            ),
            'StreamRuntimeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamRuntimeEvents,
                    request_deserializer=agent__pb2.StreamRuntimeEventsRequest.FromString,
                    response_serializer=agent__pb2.RuntimeEvent.SerializeToString,
            ),
            'SearchKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchKnowledge,
                    request_deserializer=agent__pb2.SearchKnowledgeRequest.FromString,
                    response_serializer=agent__pb2.SearchKnowledgeResponse.SerializeToString,
            ),
            'InvokeTool': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeTool,
                    request_deserializer=agent__pb2.InvokeToolRequest.FromString,
                    response_serializer=agent__pb2.InvokeToolResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=agent__pb2.HealthCheckRequest.FromString,
                    response_serializer=agent__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.v1.AgentRuntime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent.v1.AgentRuntime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentRuntime(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitUserMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.v1.AgentRuntime/SubmitUserMessage',
            agent__pb2.SubmitUserMessageRequest.SerializeToString,
            agent__pb2.SubmitUserMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamRuntimeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agent.v1.AgentRuntime/StreamRuntimeEvents',
            agent__pb2.StreamRuntimeEventsRequest.SerializeToString,
            agent__pb2.RuntimeEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.v1.AgentRuntime/SearchKnowledge',
            agent__pb2.SearchKnowledgeRequest.SerializeToString,
            agent__pb2.SearchKnowledgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvokeTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.v1.AgentRuntime/InvokeTool',
            agent__pb2.InvokeToolRequest.SerializeToString,
            agent__pb2.InvokeToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.v1.AgentRuntime/HealthCheck',
            agent__pb2.HealthCheckRequest.SerializeToString,
            agent__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ToolSandboxStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunTool = channel.unary_unary(
                '/agent.v1.ToolSandbox/RunTool',
                request_serializer=agent__pb2.RunToolRequest.SerializeToString,
                response_deserializer=agent__pb2.RunToolResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/agent.v1.ToolSandbox/HealthCheck',
                request_serializer=agent__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=agent__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class ToolSandboxServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ToolSandboxServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunTool': grpc.unary_unary_rpc_method_handler(
                    servicer.RunTool,
                    request_deserializer=agent__pb2.RunToolRequest.FromString,
                    response_serializer=agent__pb2.RunToolResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=agent__pb2.HealthCheckRequest.FromString,
                    response_serializer=agent__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.v1.ToolSandbox', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent.v1.ToolSandbox', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ToolSandbox(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.v1.ToolSandbox/RunTool',
            agent__pb2.RunToolRequest.SerializeToString,
            agent__pb2.RunToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.v1.ToolSandbox/HealthCheck',
            agent__pb2.HealthCheckRequest.SerializeToString,
            agent__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
