# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import agent_admin_pb2 as agent__admin__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_admin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentAdminStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterProfile = channel.unary_unary(
                '/agent.admin.v1.AgentAdmin/RegisterProfile',
                request_serializer=agent__admin__pb2.RegisterProfileRequest.SerializeToString,
                response_deserializer=agent__admin__pb2.Profile.FromString,
                _registered_method=True)
        self.GetProfile = channel.unary_unary(
                '/agent.admin.v1.AgentAdmin/GetProfile',
                request_serializer=agent__admin__pb2.GetProfileRequest.SerializeToString,
                response_deserializer=agent__admin__pb2.Profile.FromString,
                _registered_method=True)
        self.SetDesiredState = channel.unary_unary(
                '/agent.admin.v1.AgentAdmin/SetDesiredState',
                request_serializer=agent__admin__pb2.SetDesiredStateRequest.SerializeToString,
                response_deserializer=agent__admin__pb2.Profile.FromString,
                _registered_method=True)
        self.SetMatrixCredentialReference = channel.unary_unary(
                '/agent.admin.v1.AgentAdmin/SetMatrixCredentialReference',
                request_serializer=agent__admin__pb2.SetMatrixCredentialReferenceRequest.SerializeToString,
                response_deserializer=agent__admin__pb2.Profile.FromString,
                _registered_method=True)
        self.DeactivateMatrixCredentialReference = channel.unary_unary(
                '/agent.admin.v1.AgentAdmin/DeactivateMatrixCredentialReference',
                request_serializer=agent__admin__pb2.DeactivateMatrixCredentialReferenceRequest.SerializeToString,
                response_deserializer=agent__admin__pb2.Profile.FromString,
                _registered_method=True)
        self.RequestLifecycleOperation = channel.unary_unary(
                '/agent.admin.v1.AgentAdmin/RequestLifecycleOperation',
                request_serializer=agent__admin__pb2.RequestLifecycleOperationRequest.SerializeToString,
                response_deserializer=agent__admin__pb2.LifecycleOperation.FromString,
                _registered_method=True)
        self.GetLifecycleOperation = channel.unary_unary(
                '/agent.admin.v1.AgentAdmin/GetLifecycleOperation',
                request_serializer=agent__admin__pb2.GetLifecycleOperationRequest.SerializeToString,
                response_deserializer=agent__admin__pb2.LifecycleOperation.FromString,
                _registered_method=True)
        self.ListEvidence = channel.unary_unary(
                '/agent.admin.v1.AgentAdmin/ListEvidence',
                request_serializer=agent__admin__pb2.ListEvidenceRequest.SerializeToString,
                response_deserializer=agent__admin__pb2.ListEvidenceResponse.FromString,
                _registered_method=True)


class AgentAdminServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDesiredState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMatrixCredentialReference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeactivateMatrixCredentialReference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestLifecycleOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLifecycleOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEvidence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentAdminServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterProfile,
                    request_deserializer=agent__admin__pb2.RegisterProfileRequest.FromString,
                    response_serializer=agent__admin__pb2.Profile.SerializeToString,
            ),
            'GetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfile,
                    request_deserializer=agent__admin__pb2.GetProfileRequest.FromString,
                    response_serializer=agent__admin__pb2.Profile.SerializeToString,
            ),
            'SetDesiredState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDesiredState,
                    request_deserializer=agent__admin__pb2.SetDesiredStateRequest.FromString,
                    response_serializer=agent__admin__pb2.Profile.SerializeToString,
            ),
            'SetMatrixCredentialReference': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMatrixCredentialReference,
                    request_deserializer=agent__admin__pb2.SetMatrixCredentialReferenceRequest.FromString,
                    response_serializer=agent__admin__pb2.Profile.SerializeToString,
            ),
            'DeactivateMatrixCredentialReference': grpc.unary_unary_rpc_method_handler(
                    servicer.DeactivateMatrixCredentialReference,
                    request_deserializer=agent__admin__pb2.DeactivateMatrixCredentialReferenceRequest.FromString,
                    response_serializer=agent__admin__pb2.Profile.SerializeToString,
            ),
            'RequestLifecycleOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestLifecycleOperation,
                    request_deserializer=agent__admin__pb2.RequestLifecycleOperationRequest.FromString,
                    response_serializer=agent__admin__pb2.LifecycleOperation.SerializeToString,
            ),
            'GetLifecycleOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLifecycleOperation,
                    request_deserializer=agent__admin__pb2.GetLifecycleOperationRequest.FromString,
                    response_serializer=agent__admin__pb2.LifecycleOperation.SerializeToString,
            ),
            'ListEvidence': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEvidence,
                    request_deserializer=agent__admin__pb2.ListEvidenceRequest.FromString,
                    response_serializer=agent__admin__pb2.ListEvidenceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.admin.v1.AgentAdmin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent.admin.v1.AgentAdmin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentAdmin(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.admin.v1.AgentAdmin/RegisterProfile',
            agent__admin__pb2.RegisterProfileRequest.SerializeToString,
            agent__admin__pb2.Profile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.admin.v1.AgentAdmin/GetProfile',
            agent__admin__pb2.GetProfileRequest.SerializeToString,
            agent__admin__pb2.Profile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDesiredState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.admin.v1.AgentAdmin/SetDesiredState',
            agent__admin__pb2.SetDesiredStateRequest.SerializeToString,
            agent__admin__pb2.Profile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMatrixCredentialReference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.admin.v1.AgentAdmin/SetMatrixCredentialReference',
            agent__admin__pb2.SetMatrixCredentialReferenceRequest.SerializeToString,
            agent__admin__pb2.Profile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeactivateMatrixCredentialReference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.admin.v1.AgentAdmin/DeactivateMatrixCredentialReference',
            agent__admin__pb2.DeactivateMatrixCredentialReferenceRequest.SerializeToString,
            agent__admin__pb2.Profile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestLifecycleOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.admin.v1.AgentAdmin/RequestLifecycleOperation',
            agent__admin__pb2.RequestLifecycleOperationRequest.SerializeToString,
            agent__admin__pb2.LifecycleOperation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLifecycleOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.admin.v1.AgentAdmin/GetLifecycleOperation',
            agent__admin__pb2.GetLifecycleOperationRequest.SerializeToString,
            agent__admin__pb2.LifecycleOperation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEvidence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.admin.v1.AgentAdmin/ListEvidence',
            agent__admin__pb2.ListEvidenceRequest.SerializeToString,
            agent__admin__pb2.ListEvidenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
