# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from libs.common.proto import queue_pb2 as queue__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in queue_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QueueServiceStub(object):
    """──────────────────────────────────────────────
    Service
    ──────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Enqueue = channel.unary_unary(
                '/queue.v1.QueueService/Enqueue',
                request_serializer=queue__pb2.EnqueueRequest.SerializeToString,
                response_deserializer=queue__pb2.EnqueueResponse.FromString,
                _registered_method=True)
        self.Dequeue = channel.unary_unary(
                '/queue.v1.QueueService/Dequeue',
                request_serializer=queue__pb2.DequeueRequest.SerializeToString,
                response_deserializer=queue__pb2.DequeueResponse.FromString,
                _registered_method=True)
        self.Ack = channel.unary_unary(
                '/queue.v1.QueueService/Ack',
                request_serializer=queue__pb2.AckRequest.SerializeToString,
                response_deserializer=queue__pb2.AckResponse.FromString,
                _registered_method=True)
        self.Nack = channel.unary_unary(
                '/queue.v1.QueueService/Nack',
                request_serializer=queue__pb2.NackRequest.SerializeToString,
                response_deserializer=queue__pb2.NackResponse.FromString,
                _registered_method=True)
        self.GetMessage = channel.unary_unary(
                '/queue.v1.QueueService/GetMessage',
                request_serializer=queue__pb2.GetMessageRequest.SerializeToString,
                response_deserializer=queue__pb2.GetMessageResponse.FromString,
                _registered_method=True)
        self.ListQueues = channel.unary_unary(
                '/queue.v1.QueueService/ListQueues',
                request_serializer=queue__pb2.ListQueuesRequest.SerializeToString,
                response_deserializer=queue__pb2.ListQueuesResponse.FromString,
                _registered_method=True)
        self.Peek = channel.unary_unary(
                '/queue.v1.QueueService/Peek',
                request_serializer=queue__pb2.PeekRequest.SerializeToString,
                response_deserializer=queue__pb2.PeekResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/queue.v1.QueueService/HealthCheck',
                request_serializer=queue__pb2.QueueHealthCheckRequest.SerializeToString,
                response_deserializer=queue__pb2.QueueHealthCheckResponse.FromString,
                _registered_method=True)


class QueueServiceServicer(object):
    """──────────────────────────────────────────────
    Service
    ──────────────────────────────────────────────

    """

    def Enqueue(self, request, context):
        """Enqueue a new service request onto a named queue.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dequeue(self, request, context):
        """Claim the next pending service request from a named queue.
        Returns found=false if the queue is empty.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ack(self, request, context):
        """Acknowledge a claimed service request as successfully handled.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Nack(self, request, context):
        """Negative-acknowledge a claimed service request. Retries or sends to DLQ.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessage(self, request, context):
        """Fetch a specific service request by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListQueues(self, request, context):
        """List all queues with depth counts.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Peek(self, request, context):
        """Peek at the top N service requests in a queue without claiming them.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueueServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Enqueue': grpc.unary_unary_rpc_method_handler(
                    servicer.Enqueue,
                    request_deserializer=queue__pb2.EnqueueRequest.FromString,
                    response_serializer=queue__pb2.EnqueueResponse.SerializeToString,
            ),
            'Dequeue': grpc.unary_unary_rpc_method_handler(
                    servicer.Dequeue,
                    request_deserializer=queue__pb2.DequeueRequest.FromString,
                    response_serializer=queue__pb2.DequeueResponse.SerializeToString,
            ),
            'Ack': grpc.unary_unary_rpc_method_handler(
                    servicer.Ack,
                    request_deserializer=queue__pb2.AckRequest.FromString,
                    response_serializer=queue__pb2.AckResponse.SerializeToString,
            ),
            'Nack': grpc.unary_unary_rpc_method_handler(
                    servicer.Nack,
                    request_deserializer=queue__pb2.NackRequest.FromString,
                    response_serializer=queue__pb2.NackResponse.SerializeToString,
            ),
            'GetMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessage,
                    request_deserializer=queue__pb2.GetMessageRequest.FromString,
                    response_serializer=queue__pb2.GetMessageResponse.SerializeToString,
            ),
            'ListQueues': grpc.unary_unary_rpc_method_handler(
                    servicer.ListQueues,
                    request_deserializer=queue__pb2.ListQueuesRequest.FromString,
                    response_serializer=queue__pb2.ListQueuesResponse.SerializeToString,
            ),
            'Peek': grpc.unary_unary_rpc_method_handler(
                    servicer.Peek,
                    request_deserializer=queue__pb2.PeekRequest.FromString,
                    response_serializer=queue__pb2.PeekResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=queue__pb2.QueueHealthCheckRequest.FromString,
                    response_serializer=queue__pb2.QueueHealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'queue.v1.QueueService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('queue.v1.QueueService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QueueService(object):
    """──────────────────────────────────────────────
    Service
    ──────────────────────────────────────────────

    """

    @staticmethod
    def Enqueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queue.v1.QueueService/Enqueue',
            queue__pb2.EnqueueRequest.SerializeToString,
            queue__pb2.EnqueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Dequeue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queue.v1.QueueService/Dequeue',
            queue__pb2.DequeueRequest.SerializeToString,
            queue__pb2.DequeueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queue.v1.QueueService/Ack',
            queue__pb2.AckRequest.SerializeToString,
            queue__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Nack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queue.v1.QueueService/Nack',
            queue__pb2.NackRequest.SerializeToString,
            queue__pb2.NackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queue.v1.QueueService/GetMessage',
            queue__pb2.GetMessageRequest.SerializeToString,
            queue__pb2.GetMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListQueues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queue.v1.QueueService/ListQueues',
            queue__pb2.ListQueuesRequest.SerializeToString,
            queue__pb2.ListQueuesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Peek(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queue.v1.QueueService/Peek',
            queue__pb2.PeekRequest.SerializeToString,
            queue__pb2.PeekResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queue.v1.QueueService/HealthCheck',
            queue__pb2.QueueHealthCheckRequest.SerializeToString,
            queue__pb2.QueueHealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
