#!/bin/bash
# setup_matrix_sophia.sh
#
# Enable Sophia's Matrix appservice for a local Hub checkout.
# Generates fork-local Sophia appservice tokens in .env, registers the Sophia
# appservice with Synapse, starts the ingest receiver, and verifies the token.
#
# Usage:
#   ./scripts/setup_matrix_sophia.sh          # keep existing tokens if present
#   ./scripts/setup_matrix_sophia.sh --rotate # generate fresh Sophia tokens

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HUB_DIR="$SCRIPT_DIR/.."
ENV_FILE="$HUB_DIR/.env"
ROTATE="false"

if [ "${1:-}" = "--rotate" ]; then
  ROTATE="true"
fi

if [ ! -f "$ENV_FILE" ]; then
  echo "→ No .env found — copying from .env.example..."
  cp "$HUB_DIR/.env.example" "$ENV_FILE"
fi

python3 - "$ENV_FILE" "$ROTATE" <<'PY'
import re
import secrets
import sys
from pathlib import Path

env_path = Path(sys.argv[1])
rotate = sys.argv[2].lower() == "true"
text = env_path.read_text() if env_path.exists() else ""
lines = text.splitlines()
values = {}
for line in lines:
    match = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)=(.*)$", line)
    if match:
        values[match.group(1)] = match.group(2)

server_name = values.get("MATRIX_SERVER_NAME") or "localhost"
updates = {
    "MATRIX_REGISTER_SOPHIA_APP_SERVICE": "true",
    "SOPHIA_AS_URL": values.get("SOPHIA_AS_URL") or "http://ingest:8083",
    "SOPHIA_MATRIX_USER": values.get("SOPHIA_MATRIX_USER") or f"@sophia:{server_name}",
}

for key in ("SOPHIA_AS_TOKEN", "SOPHIA_HS_TOKEN"):
    if rotate or not values.get(key):
        updates[key] = secrets.token_hex(32)
    else:
        updates[key] = values[key]

seen = set()
out = []
for line in lines:
    match = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)=(.*)$", line)
    if match and match.group(1) in updates:
        key = match.group(1)
        out.append(f"{key}={updates[key]}")
        seen.add(key)
    else:
        out.append(line)

missing = [key for key in updates if key not in seen]
if missing:
    if out and out[-1].strip():
        out.append("")
    out.append("# Sophia Matrix appservice — generated by setup_matrix_sophia.sh")
    for key in missing:
        out.append(f"{key}={updates[key]}")

env_path.write_text("\n".join(out).rstrip() + "\n")
print("updated .env keys:")
for key in updates:
    print(f"  {key}")
PY

source "$ENV_FILE"
HOMESERVER="${MATRIX_HOMESERVER_URL:-http://localhost:${MATRIX_HTTP_PORT:-8008}}"
SOPHIA_USER="${SOPHIA_MATRIX_USER:-@sophia:${MATRIX_SERVER_NAME:-localhost}}"

echo "→ Recreating Synapse with Sophia appservice registration..."
docker compose -f "$HUB_DIR/infra/matrix/docker-compose.yml" \
  --env-file "$ENV_FILE" up -d --force-recreate matrix-synapse

echo "→ Starting Sophia ingest receiver..."
docker compose -f "$HUB_DIR/docker-compose.yml" \
  --env-file "$ENV_FILE" up -d ingest

echo "→ Waiting for Synapse health..."
for _ in $(seq 1 45); do
  if curl -sf "$HOMESERVER/health" >/dev/null 2>&1; then
    echo "  Synapse healthy"
    break
  fi
  sleep 2
done

if ! curl -sf "$HOMESERVER/health" >/dev/null 2>&1; then
  echo "ERROR: Synapse did not become healthy at $HOMESERVER" >&2
  exit 1
fi

echo "→ Verifying Sophia appservice token..."
status=$(curl -sS -o /tmp/hub-sophia-whoami.json -w '%{http_code}' \
  -H "Authorization: Bearer $SOPHIA_AS_TOKEN" \
  "$HOMESERVER/_matrix/client/v3/account/whoami?user_id=$SOPHIA_USER")

if [ "$status" != "200" ]; then
  echo "ERROR: Sophia Matrix token verification failed with HTTP $status" >&2
  python3 - <<'PY' >&2
from pathlib import Path
print(Path('/tmp/hub-sophia-whoami.json').read_text(errors='ignore'))
PY
  exit 1
fi

echo "✓ Sophia Matrix appservice token verified for $SOPHIA_USER"
