#!/bin/bash
# setup_matrix_bots.sh
#
# Full setup for gateway-bot and bridge-bot appservices.
# Generates tokens, appends values to .env, recreates Synapse so the
# container renders appservice registrations into /data/appservices, creates
# the feedback room, and appends the room ID to .env.
#
# Usage: ./scripts/setup_matrix_bots.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HUB_DIR="$SCRIPT_DIR/.."
ENV_FILE="$HUB_DIR/.env"
HOMESERVER="http://localhost:8008"
DOMAIN="${MATRIX_SERVER_NAME:-localhost}"

# ── Step 1: Generate tokens ───────────────────────────────────────────────────

echo "→ Generating tokens..."
GATEWAY_BOT_AS_TOKEN=$(openssl rand -hex 32)
GATEWAY_BOT_HS_TOKEN=$(openssl rand -hex 32)
BRIDGE_BOT_AS_TOKEN=$(openssl rand -hex 32)
BRIDGE_BOT_HS_TOKEN=$(openssl rand -hex 32)
MATRIX_GATEWAY_BOT_USER_ID="@gateway-bot:$DOMAIN"
GATEWAY_BOT_AS_URL="http://gateway-http:8080"
BRIDGE_BOT_AS_URL="http://matrix-bridge:8084"

# ── Step 2: Appservice registrations are rendered inside Synapse ───────────────

echo "→ Synapse will render appservice registrations into /data/appservices..."

# ── Step 3: Append tokens to .env ─────────────────────────────────────────────

echo "→ Appending to .env..."
cat >> "$ENV_FILE" <<ENVBLOCK

# Matrix appservice tokens — generated by setup_matrix_bots.sh
MATRIX_HOMESERVER_URL=http://localhost:8008
MATRIX_GATEWAY_BOT_USER_ID=$MATRIX_GATEWAY_BOT_USER_ID
GATEWAY_BOT_AS_TOKEN=$GATEWAY_BOT_AS_TOKEN
GATEWAY_BOT_HS_TOKEN=$GATEWAY_BOT_HS_TOKEN
BRIDGE_BOT_AS_TOKEN=$BRIDGE_BOT_AS_TOKEN
BRIDGE_BOT_HS_TOKEN=$BRIDGE_BOT_HS_TOKEN
ENVBLOCK

# ── Step 4: Recreate Synapse with appservice env ──────────────────────────────

echo "→ Recreating Synapse with rendered appservices..."
docker compose -f "$HUB_DIR/infra/matrix/docker-compose.yml" \
  --env-file "$ENV_FILE" up -d --force-recreate matrix-synapse

echo "→ Waiting for Synapse to be healthy..."
for i in $(seq 1 30); do
  if curl -sf "$HOMESERVER/health" > /dev/null 2>&1; then
    echo "  Synapse healthy"
    break
  fi
  sleep 2
done

# ── Step 6: Create feedback room ──────────────────────────────────────────────

echo "→ Creating feedback room as gateway-bot..."
ROOM_ID=$(curl -sf -X POST \
  "$HOMESERVER/_matrix/client/v3/createRoom?user_id=$MATRIX_GATEWAY_BOT_USER_ID" \
  -H "Authorization: Bearer $GATEWAY_BOT_AS_TOKEN" \
  -H "Content-Type: application/json" \
  -d "{\"name\":\"feedback\",\"preset\":\"private_chat\",\"invite\":[\"@bridge-bot:$DOMAIN\"]}" \
  | python3 -c "import sys,json; print(json.load(sys.stdin)['room_id'])")

echo "→ Bridge-bot joining room..."
curl -sf -X POST \
  "$HOMESERVER/_matrix/client/v3/join/$ROOM_ID?user_id=@bridge-bot:$DOMAIN" \
  -H "Authorization: Bearer $BRIDGE_BOT_AS_TOKEN" \
  -H "Content-Type: application/json" \
  -d "{}" > /dev/null

# ── Step 7: Append room ID to .env ────────────────────────────────────────────

echo "MATRIX_FEEDBACK_ROOM_ID=$ROOM_ID" >> "$ENV_FILE"

echo ""
echo "✓ All done. Values appended to .env, Synapse restarted, room created."
echo "  Room ID: $ROOM_ID"
